siderolabs/extras

Pkgfile
See https://github.com/talos-systems/tools/pull/110
=> feat: bump Go to 1.15.3

Pkgfile
=> chore: fix image label source repo

Pkgfile
=> feat: bump Go to 1.15.5

Pkgfile
See talos-systems/tools#115,
https://github.com/talos-systems/pkgs/pull/213.
=> feat: bump Go to 1.15.6

Pkgfile, tc-redirect-tap/pkg.yaml
See https://github.com/awslabs/tc-redirect-tap/pull/8
=> feat: build tc-redirect-tap from our fork

Pkgfile
See talos-systems/tools#126, talos-systems/pkgs#241
=> feat: bump Go to 1.15.8

Pkgfile
No changes, just aligning versions.
=> chore: bump tools and pkgs to 0.4.0

Pkgfile
See https://github.com/talos-systems/pkgs/pull/253
=> feat: bump Go to 1.15.9

Pkgfile
See https://github.com/talos-systems/pkgs/pull/254
=> feat: bump Go to 1.16.1

Pkgfile
See https://github.com/talos-systems/pkgs/pull/258
=> feat: bump Go to 1.16.2

Pkgfile
See talos-systems/tools#134 talos-systems/pkgs#260
=> feat: build with Go 1.16.3

Pkgfile
See talos-systems/tools#135, talos-systems/pkgs#286.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>
=> feat: build with Go 1.16.5

Pkgfile
There should be no actual change, just updated tags.
=> chore: update deps to final release versions

Pkgfile
See https://github.com/talos-systems/pkgs/pull/300
See https://github.com/talos-systems/tools/pull/140
=> feat: update Go to 1.16.6

Pkgfile
In preparation for Talos 0.12 release.
=> chore: update tools and pkgs to final 0.7.0

Pkgfile
To use Go 1.17.3.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>
=> chore: update pkgs and tools

Pkgfile
See:
* https://github.com/talos-systems/tools/pull/161
* https://github.com/talos-systems/pkgs/pull/365
=> feat: update Go to 1.17.4

Pkgfile
Final released versions of pkgs and tools.
=> chore: update pkgs and tools to 0.9.0

Pkgfile
See:
* https://github.com/talos-systems/tools/pull/163
* https://github.com/talos-systems/pkgs/pull/370
=> feat: update Go to 1.17.5

Pkgfile
See:
* https://github.com/talos-systems/tools/pull/168
* https://github.com/talos-systems/pkgs/pull/395
=> chore: bump to Go 1.17.7

Pkgfile
See:
* https://github.com/talos-systems/tools/pull/169
* https://github.com/talos-systems/pkgs/pull/396
=> backport: chore: update Go to 1.17.7

Pkgfile
See https://github.com/talos-systems/pkgs/pull/407
=> feat: bump pkgs for CNI 1.1.0 update

.conform.yaml, Makefile, Pkgfile
=> chore: update references after org rename

Pkgfile
Ref:
- https://github.com/siderolabs/pkgs/pull/447
=> chore: bump pkgs

Pkgfile
See https://github.com/siderolabs/pkgs/pull/446
=> feat: update pkgs for Go 1.17.9

Makefile, Pkgfile
=> chore: rename organization

Pkgfile
See https://github.com/siderolabs/pkgs/pull/471
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
=> chore: bump Go to 1.18.2

Pkgfile
In preparation for Talos 1.1.0-beta release.
=> chore: update pkg to 1.1.0

Pkgfile
See https://github.com/siderolabs/pkgs/pull/544
=> feat: update Go to 1.19

.github/renovate.json, Makefile, Pkgfile, tc-redirect-tap/pkg.yaml
=> chore: enable renovate

Pkgfile
| Package | Update | Change |
|---|---|---|
| https://github.com/awslabs/tc-redirect-tap.git | digest | `b589b55` -> `8dcd1aa` |
=> feat: update releases

Pkgfile
Release notes https://go.dev/doc/devel/release#go1.19.5
Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>
=> chore: update Go to 1.19.5

.drone.yml, .github/renovate.json, Makefile, Pkgfile
Disable renovate PR builds in CI, also fix renovate config.
=> chore: disable renovate builds

Pkgfile
=> chore: bump go

.github/renovate.json, Makefile, Pkgfile
=> chore: bump deps

Pkgfile
Bump tc-redirect-tap to `70412ed40429a56722183d1785e716765922f25a`.
=> chore: bump tc-redirect-tap

Pkgfile
=> feat: update Go to 1.19.7

Pkgfile
=> feat: update Go to 1.20.2

Pkgfile
=> chore: bump pkgs to v1.4.0

Pkgfile
=> chore: update Go to 1.20.3

Pkgfile
=> chore: update Go to 1.19.8

Pkgfile
=> backport: feat: update Go to 1.20.5

Pkgfile
Preparing for Talos 1.4.8 release.
=> chore: update go to 1.20.7

Makefile, Pkgfile
See https://go.dev/doc/devel/release#go1.21.minor
=> feat: update Go to 1.21.1

Pkgfile
=> chore: update Go to 1.21.5

Pkgfile
No other changes.
Signed-off-by: Andrey Smirnov <andrey.smirnov@siderolabs.com>
=> chore: update Go to 1.21.8

Pkgfile
=> feat: update Go to 1.22.1

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
This brings in CNI plugins 1.4.1 via pkgs.
=> chore: update base pkgs

Pkgfile
=> feat: update Go to 1.22.2

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
=> feat: update Go to 1.22.4

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Pkgfile, hack/release.sh
=> feat: bump deps

Pkgfile
=> feat: update to pkgs 1.8.0

Pkgfile
=> feat: update pkgs for 1.9

.github/workflows/ci.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
=> feat: update Go to 1.23.3

.github/workflows/ci.yaml, .github/workflows/slack-notify.yaml, .github/workflows/weekly.yaml, Makefile, Pkgfile
Update tc-redirect-tap and rekres.
=> feat: bump dependencies

.github/renovate.json, .github/workflows/ci.yaml, .github/workflows/weekly.yaml, .kres.yaml, Makefile
Bring renovate under kres control.
=> chore: kresify renovate

Pkgfile
See https://github.com/siderolabs/pkgs/pull/1146
=> fix: pull in fixed CNI plugins from pkgs
