Pkgfile

See:
* https://github.com/talos-systems/pkgs/pull/185
* https://github.com/talos-systems/tools/pull/111

feat: bump Go to 1.15.4

---

Pkgfile

chore: bump tools for Go 1.15.7 update

---

Pkgfile

chore: use 0.5.0 tagged images of pkgs and tools

---

Pkgfile

See https://github.com/talos-systems/pkgs/pull/304.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@gmail.com>

chore: update pkgs to use CNI plugins v0.9.1

---

Pkgfile

See https://github.com/talos-systems/pkgs/pull/319

chore: bump tools and packages for Go 1.16.7

---

Pkgfile

chore: update pkgs and tools

---

Pkgfile

This prepares for Talos 0.13 release.

chore: use tagged versions tools and pkgs 0.8.0

---

Pkgfile
install-cni/pkg.yaml

With changes in https://github.com/talos-systems/pkgs/pull/363, flannel
CNI plugin is now coming from a separate package.

feat: include flannel CNI plugin into install-cni package

---

Makefile
Pkgfile
base/pkg.yaml

* use `bldr` with support for `SOURCE_DATE_EPOCH`
* use `base` from `pkgs` as our build base
* remove dependency on `tools`, as `base` includes `tools`

chore: reproducible builds, use pkgs base

---

Pkgfile

Bump Golang to [1.17.11](https://github.com/siderolabs/pkgs/pull/500)

chore: bump golang to 1.17.11

---

Pkgfile

See https://github.com/siderolabs/pkgs/pull/537

backport: chore: update Go to 1.18.4

---

Pkgfile

Use 1.2.0 version targeting Talos 1.2.0.

chore: update to the final tagged pkgs

---

Pkgfile

chore: bump go to 1.19.1

---

Pkgfile
tc-redirect-tap/pkg.yaml

As my PR got merged, we can now use latest version of the CNI plugin.
(This is only used with `talosctl cluster create`/QEMU).

feat: update tc-redirect-tap to the latest version

---

Pkgfile

This brings back Flannel CNI to 1.1.2.

chore: update packages

---

Pkgfile

This PR brings in version v1.4.0-alpha.0-22-gc3a6e18 of pkgs, version 21aa6181a4c7c6b9626c271fa0f47f91e4f4a0c9 of tc_redirect_tap.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>

chore: update packages, tc_redirect_tap

---

.github/workflows/ci.yaml
.github/workflows/weekly.yaml
Makefile
Pkgfile

feat: update Go to 1.22

---

.conform.yaml
.github/workflows/ci.yaml
.github/workflows/weekly.yaml
Pkgfile

Bump pkgs to stable and rekres.

chore: bump pkgs to stable

---

.github/workflows/ci.yaml
.github/workflows/weekly.yaml
Pkgfile

Bring new Go 1.22.5 via pkgs, update `tc-redirct-tap`.
Also brings in new

feat: update dependencies

---

.github/workflows/ci.yaml
.github/workflows/weekly.yaml
Makefile
Pkgfile

- run rekres (bump buildkit to v0.15.1)
- bump bldr to v0.3.2
- bump pkgs to v1.8.0-alpha.0-45-gaf6b4e6

chore: bump deps

---

Pkgfile

Use Go1.22.6 via pkgs, also bump deps.

chore: use Go 1.22.6

---

tc-redirect-tap/pkg.yaml

Still fixing Go build changes.

fix: build tc-redirect-tap as static binary
